# .github/workflows/main.yml
name: Laravel artisan make:trait

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master & develop branches
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: cache-composer-${{ hashFiles('composer.lock') }}

      - uses: php-actions/composer@v5
        with:
          php_version: 7.2
          version: 1

      - name: Run tests
        run: |
          echo "whoami"
          whoami
          echo "groups"
          groups
          echo "ls -al vendor/orchestra/testbench-core/laravel/bootstrap"
          ls -al vendor/orchestra/testbench-core/laravel/bootstrap
          echo "ls -al vendor/orchestra/testbench-core/laravel/bootstrap/cache"
          ls -la vendor/orchestra/testbench-core/laravel/bootstrap/cache
          echo "chown -R `whoami` vendor/orchestra/testbench-core/laravel/bootstrap/*"
          chown -R `whoami` vendor/orchestra/testbench-core/laravel/bootstrap/*
          echo "ls -la vendor/orchestra/testbench-core/laravel/bootstrap"
          ls -la vendor/orchestra/testbench-core/laravel/bootstrap
          echo "ls -la vendor/orchestra/testbench-core/laravel/bootstrap/cache"
          ls -la vendor/orchestra/testbench-core/laravel/bootstrap/cache
          echo "vendor/bin/phpunit"
          vendor/bin/phpunit

  notification:
    runs-on: ubuntu-latest
    needs:  # make sure the notification is sent AFTER the jobs you want included have completed
      - unit-test
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    timeout-minutes: 60
    steps:
      - name: discord
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ github.token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
